/* omega copyright (C) 1987 by Laurence Raphael Brothers */
/* oinititem1.c */

#include <strings.h>
#include "oglob.h"

/* from oitem */
extern void potionname(),scrollname(),ringname(),stickname(),cloakname();
extern void bootname();


void inititem1();

/* initialize the item lists.... */
/* also RESET *name functions */
void inititem1()
{
  int i;
  potionname(TRUE,Str1);
  scrollname(TRUE,Str1);
  ringname(TRUE,Str1);
  stickname(TRUE,Str1);
  cloakname(TRUE,Str1);
  bootname(TRUE,Str1);

  for(i=0;i<TOTALITEMS;i++) {
    Objects[i].id = i;
    Objects[i].uniqueness = COMMON;
    Objects[i].used = FALSE;
    Objects[i].blessing = 0;
    Objects[i].plus = 0;
    Objects[i].number = 1;
    Objects[i].level = 0;
    Objects[i].aux = I_NO_OP;
    Objects[i].known = 0;
    Objects[i].dmg = 0;
    Objects[i].usef = I_NO_OP;
    strcpy(Objects[i].objstr,"Anomaly!");
    strcpy(Objects[i].truename,"Enigma!");
    strcpy(Objects[i].cursestr,"Antinomy!");
  }


  for (i=SCROLLID;i<SCROLLID+NUMSCROLLS;i++) {
    scrollname(FALSE,Objects[i].objstr);
    Objects[i].objchar = SCROLL;
    Objects[i].weight = 5;
    Objects[i].fragility = 1;
  }

  strcpy(Objects[SCROLLID+0].truename,"blank scroll"); 
  Objects[SCROLLID+0].usef = I_NOTHING;
  Objects[SCROLLID+0].level = 0;
  Objects[SCROLLID+0].basevalue = 5; 
  strcpy(Objects[SCROLLID+1].truename,"scroll of spells");
  strcpy(Objects[SCROLLID+1].cursestr,"scroll of spell loss");
  Objects[SCROLLID+1].usef = I_SPELLS;
  Objects[SCROLLID+1].level = 1;
  Objects[SCROLLID+1].basevalue = 250; 	    
  strcpy(Objects[SCROLLID+2].truename,"scroll of blessing");
  strcpy(Objects[SCROLLID+2].cursestr,"scroll of cursing");
  Objects[SCROLLID+2].usef = I_BLESS;
  Objects[SCROLLID+2].level = 2;
  Objects[SCROLLID+2].basevalue = 400;
  strcpy(Objects[SCROLLID+3].truename,"scroll of acquirement");
  strcpy(Objects[SCROLLID+3].cursestr,"scroll of destruction");
  Objects[SCROLLID+3].usef = I_ACQUIRE;
  Objects[SCROLLID+3].level = 7;
  Objects[SCROLLID+3].basevalue = 5000; 	    
  strcpy(Objects[SCROLLID+4].truename,"scroll of enchantment");
  strcpy(Objects[SCROLLID+4].cursestr,"scroll of disenchantment");
  Objects[SCROLLID+4].usef = I_ENCHANT;
  Objects[SCROLLID+4].level = 2;
  Objects[SCROLLID+4].basevalue = 200; 	    
  strcpy(Objects[SCROLLID+5].truename,"scroll of teleportation");
  strcpy(Objects[SCROLLID+5].cursestr,"scroll of teleportation");
  Objects[SCROLLID+5].usef = I_TELEPORT;
  Objects[SCROLLID+5].level = 1;
  Objects[SCROLLID+5].basevalue = 75; 	    
  strcpy(Objects[SCROLLID+6].truename,"scroll of wishing");
  strcpy(Objects[SCROLLID+6].cursestr,"scroll of wishing");
  Objects[SCROLLID+6].usef = I_WISH;
  Objects[SCROLLID+6].level = 10;
  Objects[SCROLLID+6].basevalue = 10000; 	    
  strcpy(Objects[SCROLLID+7].truename,"scroll of clairvoyance");
  strcpy(Objects[SCROLLID+7].cursestr,"scroll of amnesia");
  Objects[SCROLLID+7].usef = I_CLAIRVOYANCE;
  Objects[SCROLLID+7].level = 1;
  Objects[SCROLLID+7].basevalue = 25; 	    
  strcpy(Objects[SCROLLID+8].truename,"scroll of displacement");
  strcpy(Objects[SCROLLID+8].cursestr,"scroll of vulnerability");
  Objects[SCROLLID+8].usef = I_DISPLACE;
  Objects[SCROLLID+8].level = 2;
  Objects[SCROLLID+8].basevalue = 50; 	    
  strcpy(Objects[SCROLLID+9].truename,"scroll of identification");
  strcpy(Objects[SCROLLID+9].cursestr,"scroll of forgetfulness");
  Objects[SCROLLID+9].usef = I_ID;
  Objects[SCROLLID+9].level = 0;
  Objects[SCROLLID+9].basevalue = 20; 	    
  strcpy(Objects[SCROLLID+10].truename,"hint sheet");
  strcpy(Objects[SCROLLID+10].cursestr,"hint sheet");
  Objects[SCROLLID+10].usef = I_HINT;
  Objects[SCROLLID+10].level = 0;
  Objects[SCROLLID+10].basevalue = 10; 	    
  strcpy(Objects[SCROLLID+11].truename,"jane's guide to treasure");
  strcpy(Objects[SCROLLID+11].cursestr,"jane's guide to treasure");
  Objects[SCROLLID+11].usef = I_JANE_T;
  Objects[SCROLLID+11].level = 2;
  Objects[SCROLLID+11].basevalue = 50;
  strcpy(Objects[SCROLLID+12].truename,"scroll of alertness");
  strcpy(Objects[SCROLLID+12].cursestr,"scroll of drowsiness");
  Objects[SCROLLID+12].usef = I_ALERT;
  Objects[SCROLLID+12].level = 1;
  Objects[SCROLLID+12].basevalue = 50;
  strcpy(Objects[SCROLLID+13].truename,"scroll of cosmic flux");
  strcpy(Objects[SCROLLID+13].cursestr,"scroll of cosmic flux");
  Objects[SCROLLID+13].usef = I_FLUX;
  Objects[SCROLLID+13].level = 5;
  Objects[SCROLLID+13].basevalue = 300;
  strcpy(Objects[SCROLLID+14].truename,"scroll of charging");
  strcpy(Objects[SCROLLID+14].cursestr,"scroll of draining");
  Objects[SCROLLID+14].usef = I_CHARGE;
  Objects[SCROLLID+14].level = 2;
  Objects[SCROLLID+14].basevalue = 100;
  strcpy(Objects[SCROLLID+15].truename,"scroll of the warp");
  strcpy(Objects[SCROLLID+15].cursestr,"scroll of the warp");
  Objects[SCROLLID+15].usef = I_WARP;
  Objects[SCROLLID+15].level = 3;
  Objects[SCROLLID+15].basevalue = 100;
  strcpy(Objects[SCROLLID+16].truename,"scroll of self-knowledge");
  strcpy(Objects[SCROLLID+16].cursestr,"scroll of delusion");
  Objects[SCROLLID+16].usef = I_KNOWLEDGE;
  Objects[SCROLLID+16].level = 1;
  Objects[SCROLLID+16].basevalue = 10;
  strcpy(Objects[SCROLLID+17].truename,"scroll of law");
  strcpy(Objects[SCROLLID+17].cursestr,"scroll of law");
  Objects[SCROLLID+17].usef = I_LAW;
  Objects[SCROLLID+17].level = 2;
  Objects[SCROLLID+17].basevalue = 100;
  strcpy(Objects[SCROLLID+18].truename,"scroll of heroism");
  strcpy(Objects[SCROLLID+18].cursestr,"scroll of cowardliness");
  Objects[SCROLLID+18].usef = I_HERO;
  Objects[SCROLLID+18].level = 5;
  Objects[SCROLLID+18].basevalue = 200;
  strcpy(Objects[SCROLLID+19].truename,"scroll of true sight");
  strcpy(Objects[SCROLLID+19].cursestr,"scroll of blindness");
  Objects[SCROLLID+19].usef = I_TRUESIGHT;
  Objects[SCROLLID+19].level = 2;
  Objects[SCROLLID+19].basevalue = 50;
  strcpy(Objects[SCROLLID+20].truename,"scroll of dispelling");
  strcpy(Objects[SCROLLID+20].cursestr,"scroll of self-dispelling");
  Objects[SCROLLID+20].usef = I_DISPEL;
  Objects[SCROLLID+20].level = 3;
  Objects[SCROLLID+20].basevalue = 250;
  strcpy(Objects[SCROLLID+21].truename,"scroll of summoning");
  strcpy(Objects[SCROLLID+21].cursestr,"scroll of summoning");
  Objects[SCROLLID+21].usef = I_SUMMON;
  Objects[SCROLLID+21].level = 2;
  Objects[SCROLLID+21].basevalue = 300;
  strcpy(Objects[SCROLLID+22].truename,"scroll of light");
  strcpy(Objects[SCROLLID+22].cursestr,"scroll of darkness");
  Objects[SCROLLID+22].usef = I_ILLUMINATE;
  Objects[SCROLLID+22].level = 0;
  Objects[SCROLLID+22].basevalue = 30;


  /* aux is food value */
  for (i=FOODID;i<FOODID+NUMFOODS;i++) {
    Objects[i].objchar = FOOD;
    Objects[i].fragility = 0;
  }
  strcpy(Objects[FOODID+0].objstr,"red and white striped bucket");
  strcpy(Objects[FOODID+0].truename,"food ration");
  strcpy(Objects[FOODID+0].cursestr,"food ration");
  Objects[FOODID+0].usef = I_FOOD;
  Objects[FOODID+0].level = 0;
  Objects[FOODID+0].aux = 6;
  Objects[FOODID+0].weight = 20;
  Objects[FOODID+0].basevalue = 2; 
  strcpy(Objects[FOODID+1].truename,"wafer of lembas");
  strcpy(Objects[FOODID+1].cursestr,"wafer of lembas");
  strcpy(Objects[FOODID+1].objstr,"wafer of lembas");
  Objects[FOODID+1].usef = I_LEMBAS;
  Objects[FOODID+1].level = 2;
  Objects[FOODID+1].aux = 12;
  Objects[FOODID+1].weight = 10;
  Objects[FOODID+1].basevalue = 200; 
  strcpy(Objects[FOODID+2].truename,"stimtab");
  strcpy(Objects[FOODID+2].cursestr,"stimtab");
  strcpy(Objects[FOODID+2].objstr,"small gray tablet");
  Objects[FOODID+2].usef  = I_STIM;
  Objects[FOODID+2].aux = 0;
  Objects[FOODID+2].level  = 3;
  Objects[FOODID+2].weight = 1;
  Objects[FOODID+2].basevalue = 50; 	    
  strcpy(Objects[FOODID+3].truename,"powtab");
  strcpy(Objects[FOODID+3].cursestr,"powtab");
  strcpy(Objects[FOODID+3].objstr,"small gray tablet");
  Objects[FOODID+3].usef = I_POW;
  Objects[FOODID+3].aux = 0;
  Objects[FOODID+3].level = 3;
  Objects[FOODID+3].weight = 1;
  Objects[FOODID+3].basevalue = 100; 	    
  strcpy(Objects[FOODID+4].truename,"nutritab");
  strcpy(Objects[FOODID+4].cursestr,"nutritab");
  strcpy(Objects[FOODID+4].objstr,"small gray tablet");
  Objects[FOODID+4].usef = I_FOOD;
  Objects[FOODID+4].aux = 18;
  Objects[FOODID+4].level = 3;
  Objects[FOODID+4].weight = 1;
  Objects[FOODID+4].basevalue = 20; 	    
  strcpy(Objects[FOODID+5].truename,"immunotab");
  strcpy(Objects[FOODID+5].cursestr,"immunotab");
  strcpy(Objects[FOODID+5].objstr,"small gray tablet");
  Objects[FOODID+5].usef = I_IMMUNE;
  Objects[FOODID+5].aux = 0;
  Objects[FOODID+5].level = 3;
  Objects[FOODID+5].weight = 1;
  Objects[FOODID+5].basevalue = 500; 	    
  strcpy(Objects[FOODID+6].truename,"jelly baby");
  strcpy(Objects[FOODID+6].cursestr,"jelly baby");
  strcpy(Objects[FOODID+6].objstr,"jelly baby");
  Objects[FOODID+6].usef = I_FOOD;
  Objects[FOODID+6].aux = 2;
  Objects[FOODID+6].level = 0;
  Objects[FOODID+6].weight = 1;
  Objects[FOODID+6].basevalue = 1; 	    
  strcpy(Objects[FOODID+7].truename,"poisoned ration");
  strcpy(Objects[FOODID+7].cursestr,"poisoned ration");
  strcpy(Objects[FOODID+7].objstr,"food ration");
  Objects[FOODID+7].usef = I_POISON_FOOD;
  Objects[FOODID+7].aux = -1;
  Objects[FOODID+7].level = 1;
  Objects[FOODID+7].weight = 20;
  Objects[FOODID+7].basevalue = 25;
  strcpy(Objects[FOODID+8].truename,"szechuan pepper");
  strcpy(Objects[FOODID+8].cursestr,"szechuan pepper");
  strcpy(Objects[FOODID+8].objstr,"withered reddish stringy vegetable");
  Objects[FOODID+8].usef = I_PEPPER_FOOD;
  Objects[FOODID+8].aux = -1;
  Objects[FOODID+8].level = 2;
  Objects[FOODID+8].weight = 2;
  Objects[FOODID+8].basevalue = 100;
  strcpy(Objects[FOODID+9].truename,"pepperoni pizza pie");
  strcpy(Objects[FOODID+9].cursestr,"pepperoni pizza pie");
  strcpy(Objects[FOODID+9].objstr,"messy red and white disk");
  Objects[FOODID+9].usef = I_FOOD;
  Objects[FOODID+9].aux = 6;
  Objects[FOODID+9].level = 2;
  Objects[FOODID+9].weight = 2;
  Objects[FOODID+9].basevalue = 5;
  strcpy(Objects[FOODID+10].truename,"brown bag with strange ideograms");
  strcpy(Objects[FOODID+10].cursestr,"hunan take-out");
  strcpy(Objects[FOODID+10].objstr,"hunan take-out");
  Objects[FOODID+10].usef = I_FOOD;
  Objects[FOODID+10].aux = 6;
  Objects[FOODID+10].level = 2;
  Objects[FOODID+10].weight = 2;
  Objects[FOODID+10].basevalue = 7;
  strcpy(Objects[FOODID+11].truename,"strange foamy cylinders");
  strcpy(Objects[FOODID+11].cursestr,"twinkies");
  strcpy(Objects[FOODID+11].objstr,"twinkies");
  Objects[FOODID+11].usef = I_FOOD;
  Objects[FOODID+11].aux = 2;
  Objects[FOODID+11].level = 2;
  Objects[FOODID+11].weight = 2;
  Objects[FOODID+11].basevalue = 5;
  strcpy(Objects[FOODID+12].truename,"squiggly orange spirals");
  strcpy(Objects[FOODID+12].cursestr,"cheese-doodles");
  strcpy(Objects[FOODID+12].objstr,"cheese-doodles");
  Objects[FOODID+12].usef = I_FOOD;
  Objects[FOODID+12].aux = 2;
  Objects[FOODID+12].level = 2;
  Objects[FOODID+12].weight = 2;
  Objects[FOODID+12].basevalue = 4;
  strcpy(Objects[FOODID+13].truename,"nutty-smelling helix");
  strcpy(Objects[FOODID+13].cursestr,"pecan twirl");
  strcpy(Objects[FOODID+13].objstr,"pecal twirl");
  Objects[FOODID+13].usef = I_FOOD;
  Objects[FOODID+13].aux = 16;
  Objects[FOODID+13].level = 2;
  Objects[FOODID+13].weight = 2;
  Objects[FOODID+13].basevalue = 3;
  strcpy(Objects[FOODID+14].truename,"pale white strips with green dots");
  strcpy(Objects[FOODID+14].cursestr,"veal piccata with capers");
  strcpy(Objects[FOODID+14].objstr,"veal piccata with capers");
  Objects[FOODID+14].usef = I_FOOD;
  Objects[FOODID+14].aux = 6;
  Objects[FOODID+14].level = 2;
  Objects[FOODID+14].weight = 2;
  Objects[FOODID+14].basevalue = 75;

for (i=THINGID;i<THINGID+NUMTHINGS;i++) 
    Objects[i].objchar = THING;

  strcpy(Objects[THINGID+0].objstr,"old copper pieces");
  strcpy(Objects[THINGID+0].truename,"valuable rare coins");
  strcpy(Objects[THINGID+0].cursestr,"valuable rare coins");
  Objects[THINGID+0].weight = 20;
  Objects[THINGID+0].fragility = 10;
  Objects[THINGID+0].level = 2;
  Objects[THINGID+0].basevalue = 500;
  strcpy(Objects[THINGID+1].objstr,"some rocks");
  strcpy(Objects[THINGID+1].truename,"uncut diamonds");
  strcpy(Objects[THINGID+1].cursestr,"uncut diamonds");
  Objects[THINGID+1].fragility = 20;
  Objects[THINGID+1].weight = 20;
  Objects[THINGID+1].level = 4;
  Objects[THINGID+1].basevalue = 1000; 	    
  strcpy(Objects[THINGID+2].objstr,"twisted piece of metal");
  strcpy(Objects[THINGID+2].truename,"thieve's pick");
  strcpy(Objects[THINGID+2].cursestr,"thieve's pick");
  Objects[THINGID+2].fragility = 10;
  Objects[THINGID+2].weight = 15;
  Objects[THINGID+2].usef = I_PICK;
  Objects[THINGID+2].level = 2;
  Objects[THINGID+2].basevalue = 50;
  strcpy(Objects[THINGID+3].objstr,"large green gem");
  strcpy(Objects[THINGID+3].truename,"humongous emerald");
  strcpy(Objects[THINGID+3].cursestr,"humongous emerald");
  Objects[THINGID+3].fragility = 15;
  Objects[THINGID+3].weight = 10;
  Objects[THINGID+3].level = 1;
  Objects[THINGID+3].basevalue = 500;
  strcpy(Objects[THINGID+4].truename,"gold ingot");
  strcpy(Objects[THINGID+4].cursestr,"gold ingot");
  strcpy(Objects[THINGID+4].objstr,"gold ingot");
  Objects[THINGID+4].fragility = 18;
  Objects[THINGID+4].weight = 200;
  Objects[THINGID+4].level = 4;
  Objects[THINGID+4].basevalue = 750;
  strcpy(Objects[THINGID+5].truename,"bearer bonds");
  strcpy(Objects[THINGID+5].cursestr,"bearer bonds");
  strcpy(Objects[THINGID+5].objstr,"old illegible documents");
  Objects[THINGID+5].fragility = 1;
  Objects[THINGID+5].weight = 5;
  Objects[THINGID+5].level = 5;
  Objects[THINGID+5].basevalue = 1000;
  strcpy(Objects[THINGID+6].objstr,"bucket of salt water");
  strcpy(Objects[THINGID+6].truename,"bucket of salt water");
  strcpy(Objects[THINGID+6].cursestr,"bucket of salt water");
  Objects[THINGID+6].fragility = 1;
  Objects[THINGID+6].weight = 100;
  Objects[THINGID+6].level = 0;
  Objects[THINGID+6].basevalue = 1; 	    
  strcpy(Objects[THINGID+7].truename,"magic key");
  strcpy(Objects[THINGID+7].cursestr,"magic key");
  strcpy(Objects[THINGID+7].objstr,"key");
  Objects[THINGID+7].fragility = 10;
  Objects[THINGID+7].weight = 3;
  Objects[THINGID+7].level = 2;
  Objects[THINGID+7].usef = I_KEY;
  Objects[THINGID+7].basevalue = 20;
  strcpy(Objects[THINGID+8].objstr,"torch");
  strcpy(Objects[THINGID+8].truename,"torch");
  strcpy(Objects[THINGID+8].cursestr,"torch");
  Objects[THINGID+8].fragility = 8;
  Objects[THINGID+8].usef = I_PERM_ILLUMINATE;
  Objects[THINGID+8].level = 0;
  Objects[THINGID+8].aux = 6;
  Objects[THINGID+8].weight = 30;
  Objects[THINGID+8].basevalue = 10;
  strcpy(Objects[THINGID+9].objstr,"grot");
  strcpy(Objects[THINGID+9].truename,"grot");
  strcpy(Objects[THINGID+9].cursestr,"grot");
  Objects[THINGID+9].fragility = 12;
  Objects[THINGID+9].weight = 10;
  Objects[THINGID+9].level = 0;
  Objects[THINGID+9].basevalue = 0;
  strcpy(Objects[THINGID+10].objstr,"grot");
  strcpy(Objects[THINGID+10].truename,"grot");
  strcpy(Objects[THINGID+10].cursestr,"grot");
  Objects[THINGID+10].fragility = 12;
  Objects[THINGID+10].weight = 10;
  Objects[THINGID+10].level = 0;
  Objects[THINGID+10].basevalue = 0;
  strcpy(Objects[THINGID+11].objstr,"grot");
  strcpy(Objects[THINGID+11].truename,"grot");
  strcpy(Objects[THINGID+11].cursestr,"grot");
  Objects[THINGID+11].fragility = 12;
  Objects[THINGID+11].weight = 10;
  Objects[THINGID+11].level = 0;
  Objects[THINGID+11].basevalue = 0;
  strcpy(Objects[THINGID+12].objstr,"grot");
  strcpy(Objects[THINGID+12].truename,"grot");
  strcpy(Objects[THINGID+12].cursestr,"grot");
  Objects[THINGID+12].fragility = 12;
  Objects[THINGID+12].weight = 10;
  Objects[THINGID+12].level = 0;
  Objects[THINGID+12].basevalue = 0;
  strcpy(Objects[THINGID+13].objstr,"grot");
  strcpy(Objects[THINGID+13].truename,"grot");
  strcpy(Objects[THINGID+13].cursestr,"grot");
  Objects[THINGID+13].fragility = 12;
  Objects[THINGID+13].weight = 10;
  Objects[THINGID+13].level = 0;
  Objects[THINGID+13].basevalue = 0;
  strcpy(Objects[THINGID+14].objstr,"grot");
  strcpy(Objects[THINGID+14].truename,"grot");
  strcpy(Objects[THINGID+14].cursestr,"grot");
  Objects[THINGID+14].fragility = 12;
  Objects[THINGID+14].weight = 10;
  Objects[THINGID+14].level = 0;
  Objects[THINGID+14].basevalue = 0;
  strcpy(Objects[THINGID+15].objstr,"grot");
  strcpy(Objects[THINGID+15].truename,"grot");
  strcpy(Objects[THINGID+15].cursestr,"grot");
  Objects[THINGID+15].fragility = 12;
  Objects[THINGID+15].weight = 10;
  Objects[THINGID+15].level = 0;
  Objects[THINGID+15].basevalue = 0;
  strcpy(Objects[THINGID+16].objstr,"Morgon's Badge");
  strcpy(Objects[THINGID+16].truename,"Morgon's Badge");
  strcpy(Objects[THINGID+16].cursestr,"Morgon's Badge");
  Objects[THINGID+16].fragility = 12;
  Objects[THINGID+16].weight = 10;
  Objects[THINGID+16].level = 0;
  Objects[THINGID+16].uniqueness = UNIQUE_MADE;
  Objects[THINGID+16].basevalue = 0;
  strcpy(Objects[THINGID+17].objstr,"spring-loaded tube");
  strcpy(Objects[THINGID+17].truename,"dart-trap component");
  strcpy(Objects[THINGID+17].cursestr,"dart-trap component");
  Objects[THINGID+17].fragility = 3;
  Objects[THINGID+17].weight = 10;
  Objects[THINGID+17].level = 0;
  Objects[THINGID+17].aux = L_TRAP_DART;
  Objects[THINGID+17].usef = I_TRAP;
  Objects[THINGID+17].uniqueness = COMMON;
  Objects[THINGID+17].basevalue = 30;
  strcpy(Objects[THINGID+23].objstr,"powerful rune");
  strcpy(Objects[THINGID+23].truename,"disintegration-trap component");
  strcpy(Objects[THINGID+23].cursestr,"disintegration-trap component");
  Objects[THINGID+23].fragility = 3;
  Objects[THINGID+23].weight = 10;
  Objects[THINGID+23].level = 0;
  Objects[THINGID+23].aux = L_TRAP_DISINTEGRATE;
  Objects[THINGID+23].usef = I_TRAP;
  Objects[THINGID+23].uniqueness = COMMON;
  Objects[THINGID+23].basevalue = 30;
  strcpy(Objects[THINGID+22].objstr,"pressurized cannister");
  strcpy(Objects[THINGID+22].truename,"sleepgas-trap component");
  strcpy(Objects[THINGID+22].cursestr,"sleepgas-trap component");
  Objects[THINGID+22].fragility = 3;
  Objects[THINGID+22].weight = 10;
  Objects[THINGID+22].level = 0;
  Objects[THINGID+22].aux = L_TRAP_SLEEP_GAS;
  Objects[THINGID+22].usef = I_TRAP;
  Objects[THINGID+22].uniqueness = COMMON;
  Objects[THINGID+22].basevalue = 30;
  strcpy(Objects[THINGID+21].objstr,"powerful rune");
  strcpy(Objects[THINGID+21].truename,"teleport-trap component");
  strcpy(Objects[THINGID+21].cursestr,"teleport-trap component");
  Objects[THINGID+21].fragility = 3;
  Objects[THINGID+21].weight = 10;
  Objects[THINGID+21].level = 0;
  Objects[THINGID+21].aux = L_TRAP_TELEPORT;
  Objects[THINGID+21].usef = I_TRAP;
  Objects[THINGID+21].uniqueness = COMMON;
  Objects[THINGID+21].basevalue = 30;
  strcpy(Objects[THINGID+24].objstr,"dark fabric patch");
  strcpy(Objects[THINGID+24].truename,"abyss-trap component");
  strcpy(Objects[THINGID+24].cursestr,"abyss-trap component");
  Objects[THINGID+24].fragility = 3;
  Objects[THINGID+24].weight = 10;
  Objects[THINGID+24].level = 0;
  Objects[THINGID+24].aux = L_TRAP_ABYSS;
  Objects[THINGID+24].usef = I_TRAP;
  Objects[THINGID+24].uniqueness = COMMON;
  Objects[THINGID+24].basevalue = 30;
  strcpy(Objects[THINGID+20].objstr,"mound of powdered aluminum");
  strcpy(Objects[THINGID+20].truename,"fire-trap component");
  strcpy(Objects[THINGID+20].cursestr,"fire-trap component");
  Objects[THINGID+20].fragility = 3;
  Objects[THINGID+20].weight = 10;
  Objects[THINGID+20].level = 0;
  Objects[THINGID+20].aux = L_TRAP_FIRE;
  Objects[THINGID+20].usef = I_TRAP;
  Objects[THINGID+20].uniqueness = COMMON;
  Objects[THINGID+20].basevalue = 30;
  strcpy(Objects[THINGID+19].objstr,"coil of fine wire");
  strcpy(Objects[THINGID+19].truename,"snare component");
  strcpy(Objects[THINGID+19].cursestr,"snare component");
  Objects[THINGID+19].fragility = 3;
  Objects[THINGID+19].weight = 10;
  Objects[THINGID+19].level = 0;
  Objects[THINGID+19].aux = L_TRAP_SNARE;
  Objects[THINGID+19].usef = I_TRAP;
  Objects[THINGID+19].uniqueness = COMMON;
  Objects[THINGID+19].basevalue = 30;
  strcpy(Objects[THINGID+18].objstr,"pressurized cannister");
  strcpy(Objects[THINGID+18].truename,"acid-trap component");
  strcpy(Objects[THINGID+18].cursestr,"acid-trap component");
  Objects[THINGID+18].fragility = 3;
  Objects[THINGID+18].weight = 10;
  Objects[THINGID+18].level = 0;
  Objects[THINGID+18].aux = L_TRAP_ACID;
  Objects[THINGID+18].usef = I_TRAP;
  Objects[THINGID+18].uniqueness = COMMON;
  Objects[THINGID+18].basevalue = 30;
  strcpy(Objects[THINGID+25].objstr,"powerful rune");
  strcpy(Objects[THINGID+25].truename,"manadrain-trap component");
  strcpy(Objects[THINGID+25].cursestr,"manadrain-trap component");
  Objects[THINGID+25].fragility = 3;
  Objects[THINGID+25].weight = 10;
  Objects[THINGID+25].level = 0;
  Objects[THINGID+25].aux = L_TRAP_MANADRAIN;
  Objects[THINGID+25].usef = I_TRAP;
  Objects[THINGID+25].uniqueness = COMMON;
  Objects[THINGID+25].basevalue = 30;



  for (i=POTIONID; i<POTIONID+NUMPOTIONS;i++) {
    potionname(FALSE,Objects[i].objstr);
    Objects[i].objchar = POTION;
    Objects[i].weight = 20;
    Objects[i].fragility = 5;
  }    

  strcpy(Objects[POTIONID+0].truename,"potion of quenching thirst");
  Objects[POTIONID+1].usef = I_NOTHING;
  Objects[POTIONID+1].level = 0;
  Objects[POTIONID+1].basevalue = 0; 
  strcpy(Objects[POTIONID+1].truename,"potion of healing");
  strcpy(Objects[POTIONID+1].cursestr,"potion of disruption");
  Objects[POTIONID+1].usef = I_HEAL;
  Objects[POTIONID+1].level = 2;
  Objects[POTIONID+1].basevalue = 40; 
  strcpy(Objects[POTIONID+2].truename,"potion of object detection");
  strcpy(Objects[POTIONID+2].cursestr,"potion of object detection");
  Objects[POTIONID+2].usef = I_OBJDET;
  Objects[POTIONID+2].level = 1;
  Objects[POTIONID+2].basevalue = 10; 	    
  strcpy(Objects[POTIONID+3].truename,"potion of monster detection");
  strcpy(Objects[POTIONID+3].cursestr,"potion of monster detection");
  Objects[POTIONID+3].usef = I_MONDET;
  Objects[POTIONID+3].level = 1;
  Objects[POTIONID+3].basevalue = 10;
  strcpy(Objects[POTIONID+4].truename,"potion of neutralize poison");
  strcpy(Objects[POTIONID+4].cursestr,"potion of poison");
  Objects[POTIONID+4].usef = I_NEUTRALIZE_POISON;
  Objects[POTIONID+4].level = 2;
  Objects[POTIONID+4].basevalue = 20;
  strcpy(Objects[POTIONID+5].truename,"potion of alertness");
  strcpy(Objects[POTIONID+5].cursestr,"potion of sleep");
  Objects[POTIONID+5].usef = I_ALERT;
  Objects[POTIONID+5].level = 0;
  Objects[POTIONID+5].basevalue = 100;
  strcpy(Objects[POTIONID+6].truename,"potion of speed");
  strcpy(Objects[POTIONID+6].cursestr,"potion of slowness");
  Objects[POTIONID+6].usef = I_SPEED;
  Objects[POTIONID+6].level = 1;
  Objects[POTIONID+6].basevalue = 40; 	    
  strcpy(Objects[POTIONID+7].truename,"potion of restoration");
  strcpy(Objects[POTIONID+7].cursestr,"potion of debilitation");
  Objects[POTIONID+7].usef = I_RESTORE;
  Objects[POTIONID+7].level = 3;
  Objects[POTIONID+7].basevalue = 50; 	    
  strcpy(Objects[POTIONID+8].truename,"azoth");
  strcpy(Objects[POTIONID+8].cursestr,"mercury");
  strcpy(Objects[POTIONID+8].objstr,"mercury");
  Objects[POTIONID+8].plus = -1;
  Objects[POTIONID+8].usef = I_AZOTH;
  Objects[POTIONID+8].level = 7;
  Objects[POTIONID+8].basevalue = 1500; 	    
  strcpy(Objects[POTIONID+9].truename,"potion of regeneration");
  strcpy(Objects[POTIONID+9].cursestr,"potion of great disruption");
  Objects[POTIONID+9].usef = I_REGENERATE;
  Objects[POTIONID+9].level = 4;
  Objects[POTIONID+9].basevalue = 100; 	    
  strcpy(Objects[POTIONID+10].truename,"potion of invisibility");
  strcpy(Objects[POTIONID+10].cursestr,"potion of aggravation");
  Objects[POTIONID+10].usef = I_INVISIBLE;
  Objects[POTIONID+10].level = 2;
  Objects[POTIONID+10].basevalue = 100; 	    
  strcpy(Objects[POTIONID+11].truename,"potion of breathing");
  strcpy(Objects[POTIONID+11].cursestr,"potion of choking");
  Objects[POTIONID+11].usef = I_BREATHING;
  Objects[POTIONID+11].level = 2;
  Objects[POTIONID+11].basevalue = 30; 	    
  strcpy(Objects[POTIONID+12].truename,"potion of augmentation");
  strcpy(Objects[POTIONID+12].cursestr,"potion of debilitation");
  Objects[POTIONID+12].usef = I_AUGMENT;
  Objects[POTIONID+12].level = 5;
  Objects[POTIONID+12].basevalue = 200; 	    
  strcpy(Objects[POTIONID+13].truename,"potion of banishing fear");
  strcpy(Objects[POTIONID+13].cursestr,"potion of fear");
  Objects[POTIONID+13].usef = I_FEAR_RESIST;
  Objects[POTIONID+13].level = 2;
  Objects[POTIONID+13].basevalue = 50;
  strcpy(Objects[POTIONID+14].truename,"potion of chaos");
  strcpy(Objects[POTIONID+14].cursestr,"potion of chaos");
  Objects[POTIONID+14].usef = I_CHAOS;
  Objects[POTIONID+14].level = 3;
  Objects[POTIONID+14].basevalue = 100;
  strcpy(Objects[POTIONID+15].truename,"potion of accuracy");
  strcpy(Objects[POTIONID+15].cursestr,"potion of fuzziness");
  Objects[POTIONID+15].usef = I_ACCURACY;
  Objects[POTIONID+15].level = 3;
  Objects[POTIONID+15].basevalue = 200;
  strcpy(Objects[POTIONID+16].truename,"potion of levitation");
  strcpy(Objects[POTIONID+16].cursestr,"potion of levitation");
  Objects[POTIONID+16].usef = I_LEVITATION;
  Objects[POTIONID+16].level = 1;
  Objects[POTIONID+16].basevalue = 50;
  strcpy(Objects[POTIONID+17].truename,"potion of curing");
  strcpy(Objects[POTIONID+17].cursestr,"potion of disease");
  Objects[POTIONID+17].usef = I_CURE;
  Objects[POTIONID+17].level = 1;
  Objects[POTIONID+17].basevalue = 50;

  /* aux is defensive value */
  strcpy(Objects[SHIELDID+0].objstr,"buckler");
  Objects[SHIELDID+0].aux = 1;
  Objects[SHIELDID+0].weight = 20;
  Objects[SHIELDID+0].level = 0;
  Objects[SHIELDID+0].basevalue = 10; 
  strcpy(Objects[SHIELDID+1].objstr,"small round shield");
  Objects[SHIELDID+1].aux = 2;
  Objects[SHIELDID+1].weight = 40;
  Objects[SHIELDID+1].level = 1;
  Objects[SHIELDID+1].basevalue = 20; 
  strcpy(Objects[SHIELDID+2].objstr,"large round shield");
  Objects[SHIELDID+2].aux = 3;
  Objects[SHIELDID+2].weight = 100;
  Objects[SHIELDID+2].level = 2;
  Objects[SHIELDID+2].basevalue = 50; 	    
  strcpy(Objects[SHIELDID+3].objstr,"heater shield");
  Objects[SHIELDID+3].weight = 200;
  Objects[SHIELDID+3].level = 2;
  Objects[SHIELDID+3].aux = 4;
  Objects[SHIELDID+3].basevalue = 75; 	    
  strcpy(Objects[SHIELDID+4].objstr,"hoplon");
  Objects[SHIELDID+4].weight = 300;
  Objects[SHIELDID+4].level = 3;
  Objects[SHIELDID+4].aux = 5;
  Objects[SHIELDID+4].basevalue = 150; 
  strcpy(Objects[SHIELDID+5].objstr,"tower shield");
  Objects[SHIELDID+5].weight = 500;
  Objects[SHIELDID+5].level = 4;
  Objects[SHIELDID+5].aux = 6;
  Objects[SHIELDID+5].basevalue = 200; 	    
  strcpy(Objects[SHIELDID+6].objstr,"plasteel shield");
  Objects[SHIELDID+6].weight = 20;
  Objects[SHIELDID+6].level = 6;
  Objects[SHIELDID+6].aux = 7;
  Objects[SHIELDID+6].basevalue = 1000; 
  strcpy(Objects[SHIELDID+7].objstr,"shield of deflection");
  Objects[SHIELDID+7].weight = 200;
  Objects[SHIELDID+7].level = 7;
  Objects[SHIELDID+7].aux = 6;
  Objects[SHIELDID+7].plus = 6;
  Objects[SHIELDID+7].basevalue = 2000; 	    

  for (i=SHIELDID; i<SHIELDID+NUMSHIELDS; i++) {
    Objects[i].objchar = SHIELD;
    Objects[i].fragility = 15;
    strcpy(Objects[i].truename,Objects[i].objstr);
    strcpy(Objects[i].cursestr,Objects[i].objstr);
  }

/* aux is penalty to defense value */
/* dmg is damage absorbed */
  strcpy(Objects[ARMORID+0].objstr,"flak jacket");
  Objects[ARMORID+0].weight = 100;
  Objects[ARMORID+0].level = 0;
  Objects[ARMORID+0].aux = 0;
  Objects[ARMORID+0].dmg = 1;
  Objects[ARMORID+0].basevalue = 5; 
  strcpy(Objects[ARMORID+1].objstr,"soft leather armor");
  Objects[ARMORID+1].weight = 200;
  Objects[ARMORID+1].level = 1;
  Objects[ARMORID+1].dmg = 2;
  Objects[ARMORID+1].aux = 1;
  Objects[ARMORID+1].basevalue = 10; 
  strcpy(Objects[ARMORID+2].objstr,"cuirbouilli");
  Objects[ARMORID+2].weight = 200;
  Objects[ARMORID+2].level = 1;
  Objects[ARMORID+2].dmg = 2;
  Objects[ARMORID+2].aux = 1;
  Objects[ARMORID+2].basevalue = 30; 	    
  strcpy(Objects[ARMORID+3].objstr,"ring mail");
  Objects[ARMORID+3].weight = 300;
  Objects[ARMORID+3].level = 2;
  Objects[ARMORID+3].aux = 2;
  Objects[ARMORID+3].dmg = 3;
  Objects[ARMORID+3].basevalue = 100; 	    
  strcpy(Objects[ARMORID+4].objstr,"chain mail");
  Objects[ARMORID+4].weight = 400;
  Objects[ARMORID+4].level = 3;
  Objects[ARMORID+4].aux = 3;
  Objects[ARMORID+4].dmg = 4;
  Objects[ARMORID+4].basevalue = 200; 
  strcpy(Objects[ARMORID+5].objstr,"scale mail");
  Objects[ARMORID+5].weight = 400;
  Objects[ARMORID+5].level = 4;
  Objects[ARMORID+5].aux = 2;
  Objects[ARMORID+5].dmg = 4;
  Objects[ARMORID+5].basevalue = 300; 
  strcpy(Objects[ARMORID+6].objstr,"partial plate mail");
  Objects[ARMORID+6].weight = 400;
  Objects[ARMORID+6].level = 5;
  Objects[ARMORID+6].aux = 3;
  Objects[ARMORID+6].dmg = 5;
  Objects[ARMORID+6].basevalue = 450; 	    
  strcpy(Objects[ARMORID+7].objstr,"full plate mail");
  Objects[ARMORID+7].weight = 600;
  Objects[ARMORID+7].level = 6;
  Objects[ARMORID+7].aux = 4;
  Objects[ARMORID+7].dmg = 6;
  Objects[ARMORID+7].basevalue = 750; 
  strcpy(Objects[ARMORID+8].objstr,"plate armor");
  Objects[ARMORID+8].weight = 500;
  Objects[ARMORID+8].level = 6;
  Objects[ARMORID+8].aux = 4;
  Objects[ARMORID+8].dmg = 7;
  Objects[ARMORID+8].basevalue = 1500; 	    
  strcpy(Objects[ARMORID+9].objstr,"lamellar armor");
  Objects[ARMORID+9].weight = 200;
  Objects[ARMORID+9].level = 6;
  Objects[ARMORID+9].aux = 2;
  Objects[ARMORID+9].dmg = 5;
  Objects[ARMORID+9].basevalue = 1500; 	    
  strcpy(Objects[ARMORID+10].objstr,"mithril chain mail");
  Objects[ARMORID+10].weight = 200;
  Objects[ARMORID+10].level = 7;
  Objects[ARMORID+10].usef = I_PERM_FEAR_RESIST;
  Objects[ARMORID+10].aux = 2;
  Objects[ARMORID+10].dmg = 5;
  Objects[ARMORID+10].basevalue = 2000; 	    
  strcpy(Objects[ARMORID+11].objstr,"mithril plate armor");
  Objects[ARMORID+11].weight = 300;
  Objects[ARMORID+11].level = 7;
  Objects[ARMORID+11].usef = I_PERM_FEAR_RESIST;
  Objects[ARMORID+11].aux = 3;
  Objects[ARMORID+11].dmg = 8;
  Objects[ARMORID+11].basevalue = 3000; 	    
  strcpy(Objects[ARMORID+12].objstr,"dragonscale armor");
  Objects[ARMORID+12].weight = 500;
  Objects[ARMORID+12].usef = I_PERM_FIRE_RESIST;
  Objects[ARMORID+12].level = 7;
  Objects[ARMORID+12].aux = 3;
  Objects[ARMORID+12].dmg = 6;
  Objects[ARMORID+12].basevalue = 3000; 	    
  strcpy(Objects[ARMORID+13].objstr,"prismatrix armor");
  Objects[ARMORID+13].weight = 100;
  Objects[ARMORID+13].usef = I_PERM_ENERGY_RESIST;
  Objects[ARMORID+13].level = 8;
  Objects[ARMORID+13].aux = 2;
  Objects[ARMORID+13].dmg = 7;
  Objects[ARMORID+13].plus = 9;
  Objects[ARMORID+13].basevalue = 1000; 	        
  strcpy(Objects[ARMORID+14].objstr,"powered combat armor");
  Objects[ARMORID+14].aux = 0;
  Objects[ARMORID+14].dmg = 20;
  Objects[ARMORID+14].usef = I_PERM_BREATHING;
  Objects[ARMORID+14].level = 9;
  Objects[ARMORID+14].weight = 0;
  Objects[ARMORID+14].plus = 0;
  Objects[ARMORID+14].basevalue = 5000; 	    
  strcpy(Objects[ARMORID+15].objstr,"powered scout armor");
  Objects[ARMORID+15].aux = 0;
  Objects[ARMORID+15].dmg = 10;
  Objects[ARMORID+15].usef = I_PERM_BREATHING;
  Objects[ARMORID+15].level = 7;
  Objects[ARMORID+15].weight = 0;
  Objects[ARMORID+15].plus = 0;
  Objects[ARMORID+15].basevalue = 3000; 	    
  strcpy(Objects[ARMORID+16].objstr,"demonhide armor");
  Objects[ARMORID+16].aux = 0;
  Objects[ARMORID+16].dmg = 5;
  Objects[ARMORID+16].usef = I_PERM_ENERGY_RESIST;
  Objects[ARMORID+16].level = 3;
  Objects[ARMORID+16].weight = 100;
  Objects[ARMORID+16].plus = 5;
  Objects[ARMORID+16].blessing = -9;
  Objects[ARMORID+16].basevalue = 2000; 	    

  for (i=ARMORID;i<ARMORID+NUMARMOR;i++) {
    Objects[i].objchar = ARMOR;
    Objects[i].fragility = 20;
    strcpy(Objects[i].truename,Objects[i].objstr);
    strcpy(Objects[i].cursestr,Objects[i].objstr);
  }
}
