/* omega copyright (C) 1987 by Laurence Raphael Brothers */
/* oinititem2.c */

#include <strings.h>
#include "oglob.h"

/* from oitem */
extern void ringname(),stickname(),cloakname(),bootname(),potionname();

void inititem2();

void inititem2()
{ 
  int i;

  strcpy(Objects[WEAPONID+0].objstr,"dagger");
  strcpy(Objects[WEAPONID+0].truename,"dagger");
  strcpy(Objects[WEAPONID+0].cursestr,"dagger");
  Objects[WEAPONID+0].hit = 12;
  Objects[WEAPONID+0].type = THRUSTING;
  Objects[WEAPONID+0].dmg = 6;
  Objects[WEAPONID+0].weight = 10;
  Objects[WEAPONID+0].level = 0;
  Objects[WEAPONID+0].basevalue = 5; 
  strcpy(Objects[WEAPONID+1].objstr,"short sword");
  strcpy(Objects[WEAPONID+1].truename,"short sword");
  strcpy(Objects[WEAPONID+1].cursestr,"short sword");
  Objects[WEAPONID+1].hit = 11;
  Objects[WEAPONID+1].type = CUTTING;
  Objects[WEAPONID+1].weight = 25;
  Objects[WEAPONID+1].level = 1;
  Objects[WEAPONID+1].dmg = 8;
  Objects[WEAPONID+1].basevalue = 40; 
  strcpy(Objects[WEAPONID+2].objstr,"broad sword");
  strcpy(Objects[WEAPONID+2].truename,"broad sword");
  strcpy(Objects[WEAPONID+2].cursestr,"broad sword");
  Objects[WEAPONID+2].hit = 9;
  Objects[WEAPONID+2].type = CUTTING;
  Objects[WEAPONID+2].weight = 40;
  Objects[WEAPONID+2].level = 2;
  Objects[WEAPONID+2].dmg = 12;
  Objects[WEAPONID+2].basevalue = 90; 	    
  strcpy(Objects[WEAPONID+3].objstr,"bastard sword");
  strcpy(Objects[WEAPONID+3].truename,"bastard sword");
  strcpy(Objects[WEAPONID+3].cursestr,"bastard sword");
  Objects[WEAPONID+3].hit = 8;
  Objects[WEAPONID+3].type = CUTTING;
  Objects[WEAPONID+3].weight = 50;
  Objects[WEAPONID+3].level = 3;
  Objects[WEAPONID+3].dmg = 16;
  Objects[WEAPONID+3].basevalue = 250; 	    
  strcpy(Objects[WEAPONID+4].objstr,"katana");
  strcpy(Objects[WEAPONID+4].truename,"katana");
  strcpy(Objects[WEAPONID+4].cursestr,"katana");
  Objects[WEAPONID+4].hit = 10;
  Objects[WEAPONID+4].type = CUTTING;
  Objects[WEAPONID+4].weight = 50;
  Objects[WEAPONID+4].level = 4;
  Objects[WEAPONID+4].dmg = 16;
  Objects[WEAPONID+4].basevalue = 500; 
  strcpy(Objects[WEAPONID+5].objstr,"great-sword");
  strcpy(Objects[WEAPONID+5].truename,"great-sword");
  strcpy(Objects[WEAPONID+5].cursestr,"great-sword");
  Objects[WEAPONID+5].hit = 7;
  Objects[WEAPONID+5].type = CUTTING;
  Objects[WEAPONID+5].weight = 75;
  Objects[WEAPONID+5].level = 5;
  Objects[WEAPONID+5].dmg = 20;
  Objects[WEAPONID+5].basevalue = 400; 
  strcpy(Objects[WEAPONID+6].objstr,"epee");
  strcpy(Objects[WEAPONID+6].truename,"epee");
  strcpy(Objects[WEAPONID+6].cursestr,"epee");
  Objects[WEAPONID+6].weight = 15;
  Objects[WEAPONID+6].type = THRUSTING;
  Objects[WEAPONID+6].level = 2;
  Objects[WEAPONID+6].hit = 15;
  Objects[WEAPONID+6].dmg = 6;
  Objects[WEAPONID+6].basevalue = 50; 	    
  strcpy(Objects[WEAPONID+7].objstr,"rapier");
  strcpy(Objects[WEAPONID+7].truename,"rapier");
  strcpy(Objects[WEAPONID+7].cursestr,"rapier");
  Objects[WEAPONID+7].weight = 20;
  Objects[WEAPONID+7].type = THRUSTING;
  Objects[WEAPONID+7].level = 3;
  Objects[WEAPONID+7].hit = 13;
  Objects[WEAPONID+7].dmg = 8;
  Objects[WEAPONID+7].basevalue = 250; 
  strcpy(Objects[WEAPONID+8].objstr,"estoc");
  strcpy(Objects[WEAPONID+8].truename,"estoc");
  strcpy(Objects[WEAPONID+8].cursestr,"estoc");
  Objects[WEAPONID+8].dmg = 11;
  Objects[WEAPONID+8].type = THRUSTING;
  Objects[WEAPONID+8].weight = 25;
  Objects[WEAPONID+8].level = 5;
  Objects[WEAPONID+8].hit = 12;
  Objects[WEAPONID+8].basevalue = 500;
  strcpy(Objects[WEAPONID+9].objstr,"cutlass"); 
  strcpy(Objects[WEAPONID+9].truename,"cutlass"); 
  strcpy(Objects[WEAPONID+9].cursestr,"cutlass"); 
  Objects[WEAPONID+9].type = CUTTING;
  Objects[WEAPONID+9].hit = 8;
  Objects[WEAPONID+9].weight = 35;
  Objects[WEAPONID+9].level = 1;
  Objects[WEAPONID+9].dmg = 8;
  Objects[WEAPONID+9].basevalue = 40; 	    
  strcpy(Objects[WEAPONID+10].objstr,"hand-axe");
  strcpy(Objects[WEAPONID+10].truename,"hand-axe");
  strcpy(Objects[WEAPONID+10].cursestr,"hand-axe");
  Objects[WEAPONID+10].type = CUTTING;
  Objects[WEAPONID+10].hit = 10;
  Objects[WEAPONID+10].weight = 25;
  Objects[WEAPONID+10].level = 1;
  Objects[WEAPONID+10].dmg = 8;
  Objects[WEAPONID+10].basevalue = 50; 	    
  strcpy(Objects[WEAPONID+11].objstr,"battle-axe");
  strcpy(Objects[WEAPONID+11].truename,"battle-axe");
  strcpy(Objects[WEAPONID+11].cursestr,"battle-axe");
  Objects[WEAPONID+11].type = CUTTING;
  Objects[WEAPONID+11].weight = 50;
  Objects[WEAPONID+11].level = 2;
  Objects[WEAPONID+11].hit = 8;
  Objects[WEAPONID+11].dmg = 12;
  Objects[WEAPONID+11].basevalue = 100; 	    
  strcpy(Objects[WEAPONID+12].objstr,"great-axe");
  strcpy(Objects[WEAPONID+12].truename,"great-axe");
  strcpy(Objects[WEAPONID+12].cursestr,"great-axe");
  Objects[WEAPONID+12].weight = 100;
  Objects[WEAPONID+12].type = CUTTING;
  Objects[WEAPONID+12].level = 5;
  Objects[WEAPONID+12].hit = 7;
  Objects[WEAPONID+12].dmg = 24;
  Objects[WEAPONID+12].basevalue = 200; 	    
  strcpy(Objects[WEAPONID+13].objstr,"mace");
  strcpy(Objects[WEAPONID+13].truename,"mace");
  strcpy(Objects[WEAPONID+13].cursestr,"mace");
  Objects[WEAPONID+13].hit = 8;
  Objects[WEAPONID+13].type = STRIKING;
  Objects[WEAPONID+13].weight = 50;
  Objects[WEAPONID+13].level = 2;
  Objects[WEAPONID+13].dmg = 12;
  Objects[WEAPONID+13].basevalue = 50; 	    
  strcpy(Objects[WEAPONID+14].objstr,"war-hammer");
  strcpy(Objects[WEAPONID+14].truename,"war-hammer");
  strcpy(Objects[WEAPONID+14].cursestr,"war-hammer");
  Objects[WEAPONID+14].weight = 50;
  Objects[WEAPONID+14].type = STRIKING;
  Objects[WEAPONID+14].level = 2;
  Objects[WEAPONID+14].hit = 6;
  Objects[WEAPONID+14].dmg = 14;
  Objects[WEAPONID+14].basevalue = 60;
  strcpy(Objects[WEAPONID+15].objstr,"morning-star");
  strcpy(Objects[WEAPONID+15].truename,"morning-star");
  strcpy(Objects[WEAPONID+15].cursestr,"morning-star");
  Objects[WEAPONID+15].hit = 7;
  Objects[WEAPONID+15].type = STRIKING;
  Objects[WEAPONID+15].weight = 60;
  Objects[WEAPONID+15].level = 5;
  Objects[WEAPONID+15].dmg = 16;
  Objects[WEAPONID+15].basevalue = 150;
  strcpy(Objects[WEAPONID+16].objstr,"flail");
  strcpy(Objects[WEAPONID+16].truename,"flail");
  strcpy(Objects[WEAPONID+16].cursestr,"flail");
  Objects[WEAPONID+16].hit = 7;
  Objects[WEAPONID+16].type = STRIKING;
  Objects[WEAPONID+16].weight = 50;
  Objects[WEAPONID+16].level = 3;
  Objects[WEAPONID+16].dmg = 12;
  Objects[WEAPONID+16].basevalue = 50; 	    
  strcpy(Objects[WEAPONID+17].objstr,"club");
  strcpy(Objects[WEAPONID+17].truename,"club");
  strcpy(Objects[WEAPONID+17].cursestr,"club");
  Objects[WEAPONID+17].hit = 10;
  Objects[WEAPONID+17].type = STRIKING;
  Objects[WEAPONID+17].weight = 30;
  Objects[WEAPONID+17].level = 0;
  Objects[WEAPONID+17].dmg = 6;
  Objects[WEAPONID+17].basevalue = 5; 	    
  strcpy(Objects[WEAPONID+18].objstr,"quarterstaff");
  strcpy(Objects[WEAPONID+18].truename,"quarterstaff");
  strcpy(Objects[WEAPONID+18].cursestr,"quarterstaff");
  Objects[WEAPONID+18].hit = 12;
  Objects[WEAPONID+18].type = STRIKING;
  Objects[WEAPONID+18].weight = 80;
  Objects[WEAPONID+18].level = 1;
  Objects[WEAPONID+18].dmg = 9;
  Objects[WEAPONID+18].basevalue = 30;
  strcpy(Objects[WEAPONID+19].objstr,"spear");
  strcpy(Objects[WEAPONID+19].truename,"spear");
  strcpy(Objects[WEAPONID+19].cursestr,"spear");
  Objects[WEAPONID+19].hit = 10;
  Objects[WEAPONID+19].type = THRUSTING;
  Objects[WEAPONID+19].weight = 50;
  Objects[WEAPONID+19].level = 2;
  Objects[WEAPONID+19].dmg = 10;
  Objects[WEAPONID+19].basevalue = 50;
  strcpy(Objects[WEAPONID+20].objstr,"halberd");
  strcpy(Objects[WEAPONID+20].truename,"halberd");
  strcpy(Objects[WEAPONID+20].cursestr,"halberd");
  Objects[WEAPONID+20].hit = 6;
  Objects[WEAPONID+20].type = CUTTING;
  Objects[WEAPONID+20].weight = 100;
  Objects[WEAPONID+20].level = 3;
  Objects[WEAPONID+20].dmg = 16;
  Objects[WEAPONID+20].basevalue = 100; 	    
  strcpy(Objects[WEAPONID+21].objstr,"trident");
  strcpy(Objects[WEAPONID+21].truename,"trident");
  strcpy(Objects[WEAPONID+21].cursestr,"trident");
  Objects[WEAPONID+21].hit = 7;
  Objects[WEAPONID+21].type = THRUSTING;
  Objects[WEAPONID+21].weight = 80;
  Objects[WEAPONID+21].level = 3;
  Objects[WEAPONID+21].dmg = 12;
  Objects[WEAPONID+21].basevalue = 75;
  strcpy(Objects[WEAPONID+22].objstr,"whip");
  strcpy(Objects[WEAPONID+22].truename,"whip");
  strcpy(Objects[WEAPONID+22].cursestr,"whip");
  Objects[WEAPONID+22].hit = 8;
  Objects[WEAPONID+22].type = STRIKING;
  Objects[WEAPONID+22].weight = 20;
  Objects[WEAPONID+22].level = 2;
  Objects[WEAPONID+22].aux = I_TANGLE;
  Objects[WEAPONID+22].dmg = 4;
  Objects[WEAPONID+22].basevalue = 100;
  strcpy(Objects[WEAPONID+23].objstr,"grey metal cylinder");
  strcpy(Objects[WEAPONID+23].cursestr,"lightsabre");
  strcpy(Objects[WEAPONID+23].truename,"lightsabre");
  Objects[WEAPONID+23].hit = 20;
  Objects[WEAPONID+23].type = THRUSTING;
  Objects[WEAPONID+23].weight = 20;
  Objects[WEAPONID+23].level = 9;
  Objects[WEAPONID+23].usef = I_LIGHTSABRE;
  Objects[WEAPONID+23].aux = I_LIGHTSABRE;
  Objects[WEAPONID+23].plus = 0;
  Objects[WEAPONID+23].dmg = 30;
  Objects[WEAPONID+23].basevalue = 2000;
  strcpy(Objects[WEAPONID+24].objstr,"bastard sword");
  strcpy(Objects[WEAPONID+24].truename,"Demonblade");
  strcpy(Objects[WEAPONID+24].cursestr,"Demonblade");
  Objects[WEAPONID+36].uniqueness = UNIQUE_UNMADE;
  Objects[WEAPONID+36].type = CUTTING;
  Objects[WEAPONID+24].hit = 8;
  Objects[WEAPONID+24].blessing = -8;
  Objects[WEAPONID+24].plus = 8;
  Objects[WEAPONID+24].weight = 500;
  Objects[WEAPONID+24].usef = I_DEMONBLADE;
  Objects[WEAPONID+24].aux = I_DEMONBLADE;
  Objects[WEAPONID+24].level = 9;
  Objects[WEAPONID+24].dmg = 16;
  Objects[WEAPONID+24].basevalue = 1000; 	    
  strcpy(Objects[WEAPONID+25].objstr,"mace");
  strcpy(Objects[WEAPONID+25].truename,"mace of disruption");
  strcpy(Objects[WEAPONID+25].cursestr,"mace");
  Objects[WEAPONID+25].hit = 10;
  Objects[WEAPONID+25].type = STRIKING;
  Objects[WEAPONID+25].blessing = 9;
  Objects[WEAPONID+25].plus = 3;
  Objects[WEAPONID+25].weight = 250;
  Objects[WEAPONID+25].usef = I_MACE_DISRUPT;
  Objects[WEAPONID+25].aux = I_MACE_DISRUPT;
  Objects[WEAPONID+25].level = 5;
  Objects[WEAPONID+25].dmg = 12;
  Objects[WEAPONID+25].basevalue = 3000; 	    
  strcpy(Objects[WEAPONID+26].objstr,"longbow");
  strcpy(Objects[WEAPONID+26].truename,"longbow");
  strcpy(Objects[WEAPONID+26].cursestr,"longbow");
  Objects[WEAPONID+26].hit = 15;
  Objects[WEAPONID+26].type = MISSILE;
  Objects[WEAPONID+26].objchar = MISSILEWEAPON;
  Objects[WEAPONID+26].weight = 100;
  Objects[WEAPONID+26].level = 2;
  Objects[WEAPONID+26].dmg = 12;
  Objects[WEAPONID+26].basevalue = 300;
  strcpy(Objects[WEAPONID+27].objstr,"crossbow");
  strcpy(Objects[WEAPONID+27].truename,"crossbow");
  strcpy(Objects[WEAPONID+27].cursestr,"crossbow");
  Objects[WEAPONID+27].hit = 15;
  Objects[WEAPONID+27].type = MISSILE;
  Objects[WEAPONID+27].objchar = MISSILEWEAPON;
  Objects[WEAPONID+27].weight = 150;
  Objects[WEAPONID+27].level = 3;
  Objects[WEAPONID+27].dmg = 20;
  Objects[WEAPONID+27].basevalue = 500; 	    
  strcpy(Objects[WEAPONID+28].objstr,"arrow");
  strcpy(Objects[WEAPONID+28].truename,"arrow");
  strcpy(Objects[WEAPONID+28].cursestr,"arrow");
  Objects[WEAPONID+28].type = MISSILE;
  Objects[WEAPONID+28].objchar = MISSILEWEAPON;
  Objects[WEAPONID+28].hit = 3;
  Objects[WEAPONID+28].weight = 2;
  Objects[WEAPONID+28].aux = I_ARROW;
  Objects[WEAPONID+28].level = 1;
  Objects[WEAPONID+28].dmg = 3;
  Objects[WEAPONID+28].basevalue = 2;
  strcpy(Objects[WEAPONID+29].objstr,"bolt");
  strcpy(Objects[WEAPONID+29].truename,"bolt");
  strcpy(Objects[WEAPONID+29].cursestr,"bolt");
  Objects[WEAPONID+29].type = MISSILE;
  Objects[WEAPONID+29].weight = 2;
  Objects[WEAPONID+29].aux = I_BOLT;
  Objects[WEAPONID+29].objchar = MISSILEWEAPON;
  Objects[WEAPONID+29].level = 1;
  Objects[WEAPONID+29].dmg = 3;
  Objects[WEAPONID+30].hit = 3;
  Objects[WEAPONID+29].basevalue = 5; 	    
  strcpy(Objects[WEAPONID+30].objstr,"bola");
  strcpy(Objects[WEAPONID+30].truename,"bola");
  strcpy(Objects[WEAPONID+30].cursestr,"bola");
  Objects[WEAPONID+30].weight = 50;  
  Objects[WEAPONID+30].type = MISSILE;
  Objects[WEAPONID+30].objchar = MISSILEWEAPON;
  Objects[WEAPONID+30].level = 2;
  Objects[WEAPONID+30].aux = I_TANGLE;
  Objects[WEAPONID+30].hit = 10;
  Objects[WEAPONID+30].dmg = 3;
  Objects[WEAPONID+30].basevalue = 50;
  strcpy(Objects[WEAPONID+31].objstr,"broad sword");
  strcpy(Objects[WEAPONID+31].truename,"vorpal sword");
  strcpy(Objects[WEAPONID+31].cursestr,"sword of self-mutilation");
  Objects[WEAPONID+31].weight = 40;
  Objects[WEAPONID+31].type = CUTTING;
  Objects[WEAPONID+31].level = 7;
  Objects[WEAPONID+31].aux = I_VORPAL;
  Objects[WEAPONID+31].hit = 9;
  Objects[WEAPONID+31].dmg = 12;
  Objects[WEAPONID+31].plus = 5;
  Objects[WEAPONID+31].basevalue = 3000;
  strcpy(Objects[WEAPONID+32].objstr,"great-sword");
  strcpy(Objects[WEAPONID+32].truename,"Desecrator");
  strcpy(Objects[WEAPONID+32].cursestr,"Desecrator");
  Objects[WEAPONID+32].uniqueness = UNIQUE_UNMADE;
  Objects[WEAPONID+32].type = CUTTING;
  Objects[WEAPONID+32].weight = 100;
  Objects[WEAPONID+32].level = 9;
  Objects[WEAPONID+32].aux = I_DESECRATE;
  Objects[WEAPONID+32].usef = I_DESECRATE;
  Objects[WEAPONID+32].hit = 7;
  Objects[WEAPONID+32].plus = 7;
  Objects[WEAPONID+32].blessing = -7;
  Objects[WEAPONID+32].dmg = 20;
  Objects[WEAPONID+32].basevalue = 5000;
  strcpy(Objects[WEAPONID+33].objstr,"morning-star");
  strcpy(Objects[WEAPONID+33].truename,"firestar");
  strcpy(Objects[WEAPONID+33].cursestr,"firestar");
  Objects[WEAPONID+33].weight = 60;
  Objects[WEAPONID+33].type = STRIKING;
  Objects[WEAPONID+33].level = 6;
  Objects[WEAPONID+33].aux = I_FIRESTAR;
  Objects[WEAPONID+33].usef = I_PERM_FIRE_RESIST;
  Objects[WEAPONID+33].hit = 7;
  Objects[WEAPONID+33].plus = 7;
  Objects[WEAPONID+33].dmg = 16;
  Objects[WEAPONID+33].basevalue = 2000;
  strcpy(Objects[WEAPONID+34].objstr,"estoc");
  strcpy(Objects[WEAPONID+34].truename,"Defender");
  strcpy(Objects[WEAPONID+34].cursestr,"Defender");
  Objects[WEAPONID+34].uniqueness = UNIQUE_MADE;
  Objects[WEAPONID+34].type = THRUSTING;
  Objects[WEAPONID+34].weight = 50;
  Objects[WEAPONID+34].level = 7;
  Objects[WEAPONID+34].aux = I_DEFEND;
  Objects[WEAPONID+34].usef = I_DEFEND;
  Objects[WEAPONID+34].hit = 12;
  Objects[WEAPONID+34].plus = 7;
  Objects[WEAPONID+34].blessing = 7;
  Objects[WEAPONID+34].dmg = 10;
  Objects[WEAPONID+34].basevalue = 3000;
  strcpy(Objects[WEAPONID+35].objstr,"ivory spear");
  strcpy(Objects[WEAPONID+35].truename,"Victrix");
  strcpy(Objects[WEAPONID+35].cursestr,"Victrix");
  Objects[WEAPONID+35].weight = 50;
  Objects[WEAPONID+35].type = THRUSTING;
  Objects[WEAPONID+35].level = 9;
  Objects[WEAPONID+35].aux = I_VICTRIX;
  Objects[WEAPONID+35].usef = I_VICTRIX;
  Objects[WEAPONID+35].hit = 10;
  Objects[WEAPONID+35].plus = 10;
  Objects[WEAPONID+35].blessing = 10;
  Objects[WEAPONID+35].dmg = 100;
  Objects[WEAPONID+35].basevalue = 5000;
  strcpy(Objects[WEAPONID+36].objstr,"great-axe");
  strcpy(Objects[WEAPONID+36].truename,"Goblins' Hewer");
  strcpy(Objects[WEAPONID+36].cursestr,"Goblins' Hewer");
  Objects[WEAPONID+36].uniqueness = UNIQUE_MADE;
  Objects[WEAPONID+36].type = CUTTING;
  Objects[WEAPONID+36].weight = 500;
  Objects[WEAPONID+36].level = 7;
  Objects[WEAPONID+36].hit = 6;
  Objects[WEAPONID+36].plus = 6;
  Objects[WEAPONID+36].blessing = 0;
  Objects[WEAPONID+36].dmg = 32;
  Objects[WEAPONID+36].basevalue = 2000;
  strcpy(Objects[WEAPONID+37].objstr,"shortsword");
  strcpy(Objects[WEAPONID+37].truename,"The Dark Emperor's Sword");
  strcpy(Objects[WEAPONID+37].cursestr,"The Dark Emperor's Sword");
  Objects[WEAPONID+37].uniqueness = UNIQUE_MADE;
  Objects[WEAPONID+37].type = CUTTING;
  Objects[WEAPONID+37].weight = 25;
  Objects[WEAPONID+37].level = 10;
  Objects[WEAPONID+37].hit = 10;
  Objects[WEAPONID+37].plus = 20;
  Objects[WEAPONID+37].blessing = -10;
  Objects[WEAPONID+37].dmg = 10;
  Objects[WEAPONID+37].basevalue = 10000;


  for (i=WEAPONID;i<WEAPONID+NUMWEAPONS;i++) {
    if (Objects[i].objchar != MISSILEWEAPON)
      Objects[i].objchar = WEAPON;
    Objects[i].fragility = 15;
  }

  for (i=ARTIFACTID;i<ARTIFACTID+NUMARTIFACTS;i++) {
    Objects[i].objchar = ARTIFACT;
    Objects[i].fragility = 15;
  }

  strcpy(Objects[ARTIFACTID+0].objstr,"Shining Orb");
  strcpy(Objects[ARTIFACTID+0].truename,"Orb of Mastery");
  strcpy(Objects[ARTIFACTID+0].cursestr,"Orb of Mastery");
  Objects[ARTIFACTID+0].usef = I_ORBMASTERY;
  Objects[ARTIFACTID+5].uniqueness = 3;
  Objects[ARTIFACTID+0].level = 10;
  Objects[ARTIFACTID+0].weight = 500;
  Objects[ARTIFACTID+0].basevalue = 10000;
  strcpy(Objects[ARTIFACTID+1].objstr,"Red Orb");
  strcpy(Objects[ARTIFACTID+1].truename,"Orb of Fire");
  strcpy(Objects[ARTIFACTID+1].cursestr,"Orb of Fire");
  Objects[ARTIFACTID+1].usef = I_ORBFIRE;
  Objects[ARTIFACTID+1].level = 9;
  Objects[ARTIFACTID+1].weight = 50;
  Objects[ARTIFACTID+1].basevalue = 2000;
  strcpy(Objects[ARTIFACTID+2].objstr,"Green Orb");
  strcpy(Objects[ARTIFACTID+2].truename,"Orb of Water");
  strcpy(Objects[ARTIFACTID+2].cursestr,"Orb of Water");
  Objects[ARTIFACTID+2].usef = I_ORBWATER;
  Objects[ARTIFACTID+2].weight = 50;
  Objects[ARTIFACTID+2].level = 8;
  Objects[ARTIFACTID+2].basevalue = 2000;
  strcpy(Objects[ARTIFACTID+3].objstr,"Brown Orb");
  strcpy(Objects[ARTIFACTID+3].truename,"Orb of Earth");
  strcpy(Objects[ARTIFACTID+3].cursestr,"Orb of Earth");
  Objects[ARTIFACTID+3].usef = I_ORBEARTH;
  Objects[ARTIFACTID+3].level = 7;
  Objects[ARTIFACTID+3].weight = 50;
  Objects[ARTIFACTID+3].basevalue = 2000;
  strcpy(Objects[ARTIFACTID+4].objstr,"Blue Orb");
  strcpy(Objects[ARTIFACTID+4].truename,"Orb of Air");
  strcpy(Objects[ARTIFACTID+4].cursestr,"Orb of Air");
  Objects[ARTIFACTID+4].usef = I_ORBAIR;
  Objects[ARTIFACTID+4].level = 6;
  Objects[ARTIFACTID+4].weight = 50;
  Objects[ARTIFACTID+4].basevalue = 2000;
  strcpy(Objects[ARTIFACTID+5].objstr,"Black Orb");
  strcpy(Objects[ARTIFACTID+5].truename,"Burnt-out Orb");
  strcpy(Objects[ARTIFACTID+5].cursestr,"Burnt-out Orb");
  Objects[ARTIFACTID+5].usef = I_ORBDEAD;
  Objects[ARTIFACTID+5].level = 1;
  Objects[ARTIFACTID+5].weight = 25;
  Objects[ARTIFACTID+5].basevalue = 100;
  strcpy(Objects[ARTIFACTID+6].objstr,"Glass Orb");
  strcpy(Objects[ARTIFACTID+6].truename,"Crystal Ball");
  strcpy(Objects[ARTIFACTID+6].cursestr,"Ball of Mindlessness");
  Objects[ARTIFACTID+6].usef = I_CRYSTAL;
  Objects[ARTIFACTID+5].uniqueness = UNIQUE_UNMADE;
  Objects[ARTIFACTID+6].weight = 75;
  Objects[ARTIFACTID+6].level = 3;
  Objects[ARTIFACTID+6].basevalue = 500;
  strcpy(Objects[ARTIFACTID+7].objstr,"Metal Pineapple");
  strcpy(Objects[ARTIFACTID+7].truename,"Holy Hand-Grenade of Antioch");
  strcpy(Objects[ARTIFACTID+7].cursestr,"Holy Hand-Grenade of Antioch");
  Objects[ARTIFACTID+7].usef = I_ANTIOCH;
  Objects[ARTIFACTID+7].uniqueness = UNIQUE_UNMADE;
  Objects[ARTIFACTID+7].level = 5;
  Objects[ARTIFACTID+7].weight = 25;
  Objects[ARTIFACTID+7].basevalue = 1000;
  strcpy(Objects[ARTIFACTID+8].objstr,"The Amulet of Yendor");
  strcpy(Objects[ARTIFACTID+8].truename,"The Amulet of Yendor");
  strcpy(Objects[ARTIFACTID+8].cursestr,"The Amulet of Yendor");
  Objects[ARTIFACTID+8].uniqueness = COMMON;
  Objects[ARTIFACTID+8].usef = I_NOTHING;
  Objects[ARTIFACTID+8].weight = 500;
  Objects[ARTIFACTID+8].level = 1;
  Objects[ARTIFACTID+8].basevalue = 1;
  strcpy(Objects[ARTIFACTID+9].objstr,"Key");
  strcpy(Objects[ARTIFACTID+9].truename,"Kolwynia, the Key That Was Lost");
  strcpy(Objects[ARTIFACTID+9].cursestr,"Kolwynia, the Key That was Lost");
  Objects[ARTIFACTID+9].uniqueness = UNIQUE_UNMADE;
  Objects[ARTIFACTID+9].usef = I_KOLWYNIA;
  Objects[ARTIFACTID+9].weight = 1;
  Objects[ARTIFACTID+9].level = 7;
  Objects[ARTIFACTID+9].basevalue = 5000;
  potionname(FALSE,Objects[ARTIFACTID+10].objstr);
  strcpy(Objects[ARTIFACTID+10].truename,"Potion of Death");
  strcpy(Objects[ARTIFACTID+10].cursestr,"Potion of Death");
  Objects[ARTIFACTID+10].usef = I_DEATH;
  Objects[ARTIFACTID+10].uniqueness = UNIQUE_UNMADE;
  Objects[ARTIFACTID+10].weight = 10;
  Objects[ARTIFACTID+10].level = 3;
  Objects[ARTIFACTID+10].basevalue = 500;
  strcpy(Objects[ARTIFACTID+11].objstr,"Scintillating Staff");
  strcpy(Objects[ARTIFACTID+11].truename,"Staff of Enchantment");
  strcpy(Objects[ARTIFACTID+11].cursestr,"Staff of Enchantment");
  Objects[ARTIFACTID+11].usef = I_ENCHANTMENT;
  Objects[ARTIFACTID+11].uniqueness = UNIQUE_UNMADE;
  Objects[ARTIFACTID+11].level = 5;
  Objects[ARTIFACTID+11].weight = 100;
  Objects[ARTIFACTID+11].basevalue = 2000;
  strcpy(Objects[ARTIFACTID+12].objstr,"Strange Weightless Helm");
  strcpy(Objects[ARTIFACTID+12].truename,"Helm of Teleportation");
  strcpy(Objects[ARTIFACTID+12].cursestr,"Helm of Teleportation");
  Objects[ARTIFACTID+12].usef = I_HELM;
  Objects[ARTIFACTID+12].weight = 0;
  Objects[ARTIFACTID+12].level = 2;
  Objects[ARTIFACTID+12].uniqueness = UNIQUE_UNMADE;
  Objects[ARTIFACTID+12].basevalue = 1500;
  potionname(FALSE,Objects[ARTIFACTID+13].objstr);
  strcpy(Objects[ARTIFACTID+13].truename,"Potion of Life");
  strcpy(Objects[ARTIFACTID+13].cursestr,"Potion of Life");
  Objects[ARTIFACTID+13].usef = I_LIFE;
  Objects[ARTIFACTID+13].weight = 10;
  Objects[ARTIFACTID+13].uniqueness = UNIQUE_UNMADE;
  Objects[ARTIFACTID+13].level = 1;
  Objects[ARTIFACTID+13].basevalue = 500;
  strcpy(Objects[ARTIFACTID+14].truename,"Silver Gallows");
  strcpy(Objects[ARTIFACTID+14].objstr,"Holy Symbol of Odin");
  strcpy(Objects[ARTIFACTID+14].cursestr,"Holy Symbol of Odin");
  Objects[ARTIFACTID+14].usef = I_SYMBOL;
  Objects[ARTIFACTID+14].weight = 5;
  Objects[ARTIFACTID+14].aux = ODIN;
  Objects[ARTIFACTID+14].uniqueness = UNIQUE_MADE;
  Objects[ARTIFACTID+14].level = 10;
  Objects[ARTIFACTID+14].basevalue = 5000;
  strcpy(Objects[ARTIFACTID+15].truename,"Obsidian Crescent");
  strcpy(Objects[ARTIFACTID+15].objstr,"Holy Symbol of Hecate");
  strcpy(Objects[ARTIFACTID+15].cursestr,"Holy Symbol of Hecate");
  Objects[ARTIFACTID+15].usef = I_SYMBOL;
  Objects[ARTIFACTID+15].aux = HECATE;
  Objects[ARTIFACTID+15].weight = 5;
  Objects[ARTIFACTID+15].uniqueness = UNIQUE_MADE;
  Objects[ARTIFACTID+15].level = 10;
  Objects[ARTIFACTID+15].basevalue = 5000;
  strcpy(Objects[ARTIFACTID+16].truename,"Gold Owl Pendant");
  strcpy(Objects[ARTIFACTID+16].objstr,"Holy Symbol of Athena");
  strcpy(Objects[ARTIFACTID+16].cursestr,"Holy Symbol of Athena");
  Objects[ARTIFACTID+16].usef = I_SYMBOL;
  Objects[ARTIFACTID+16].aux = ATHENA;
  Objects[ARTIFACTID+16].uniqueness = UNIQUE_MADE;
  Objects[ARTIFACTID+16].weight = 5;
  Objects[ARTIFACTID+16].level = 10;
  Objects[ARTIFACTID+16].basevalue = 5000;
  strcpy(Objects[ARTIFACTID+17].truename,"Jet Scarab");
  strcpy(Objects[ARTIFACTID+17].objstr,"Holy Symbol of Set");
  strcpy(Objects[ARTIFACTID+17].cursestr,"Holy Symbol of Set");
  Objects[ARTIFACTID+17].usef = I_SYMBOL;
  Objects[ARTIFACTID+17].aux = SET;
  Objects[ARTIFACTID+17].uniqueness = UNIQUE_MADE;
  Objects[ARTIFACTID+17].weight = 5;
  Objects[ARTIFACTID+17].level = 10;
  Objects[ARTIFACTID+17].basevalue = 5000;
  strcpy(Objects[ARTIFACTID+18].truename,"Sprig of Mistletoe");
  strcpy(Objects[ARTIFACTID+18].objstr,"Holy Symbol of Druidism");
  strcpy(Objects[ARTIFACTID+18].cursestr,"Holy Symbol of Druidism");
  Objects[ARTIFACTID+18].usef = I_SYMBOL;
  Objects[ARTIFACTID+18].aux = DRUID;
  Objects[ARTIFACTID+18].weight = 5;
  Objects[ARTIFACTID+18].uniqueness = UNIQUE_MADE;
  Objects[ARTIFACTID+18].level = 10;
  Objects[ARTIFACTID+18].basevalue = 5000;
  strcpy(Objects[ARTIFACTID+19].truename,"Blue Crystal Pendant");
  strcpy(Objects[ARTIFACTID+19].objstr,"Holy Symbol of Destiny");
  strcpy(Objects[ARTIFACTID+19].cursestr,"Holy Symbol of Destiny");
  Objects[ARTIFACTID+19].usef = I_SYMBOL;
  Objects[ARTIFACTID+19].aux = DESTINY;
  Objects[ARTIFACTID+19].weight = 5;
  Objects[ARTIFACTID+19].uniqueness = UNIQUE_MADE;
  Objects[ARTIFACTID+19].level = 10;
  Objects[ARTIFACTID+19].basevalue = 5000;

  strcpy(Objects[ARTIFACTID+20].objstr,"Crudely Carved Monolith");
  strcpy(Objects[ARTIFACTID+20].truename,"The Juggernaut of Karnak");
  strcpy(Objects[ARTIFACTID+20].cursestr,"The Juggernaut of Karnak");
  Objects[ARTIFACTID+20].usef = I_JUGGERNAUT;
  Objects[ARTIFACTID+20].uniqueness = UNIQUE_UNMADE;
  Objects[ARTIFACTID+20].level = 6;
  Objects[ARTIFACTID+20].weight = 1000;
  Objects[ARTIFACTID+20].basevalue = 1000;

  for (i=STICKID;i<STICKID+NUMSTICKS;i++) {
    Objects[i].objchar = STICK;
    stickname(FALSE,Objects[i].objstr);
    Objects[i].weight = 80;
    Objects[i].fragility = 10;
  }

  strcpy(Objects[STICKID+0].truename,"staff of firebolts");
  strcpy(Objects[STICKID+0].cursestr,"staff of firebolts");
  Objects[STICKID+0].usef=I_FIREBOLT;
  Objects[STICKID+0].level = 3;
  Objects[STICKID+0].basevalue = 500;
  strcpy(Objects[STICKID+1].truename,"walking stick");
  strcpy(Objects[STICKID+1].cursestr,"walking stick");
  Objects[STICKID+1].usef=I_NOTHING;
  Objects[STICKID+1].level=0;
  Objects[STICKID+1].basevalue = 10;
  strcpy(Objects[STICKID+2].truename,"staff of sleep");
  strcpy(Objects[STICKID+2].cursestr,"staff of sleep");
  Objects[STICKID+2].usef=I_SLEEP_OTHER;
  Objects[STICKID+2].level=1;
  Objects[STICKID+2].basevalue = 100;
  strcpy(Objects[STICKID+3].truename,"wand of ball lightning");
  strcpy(Objects[STICKID+3].cursestr,"wand of ball lightning");
  Objects[STICKID+3].usef=I_LBALL;
  Objects[STICKID+3].level=4;
  Objects[STICKID+3].basevalue = 500;
  strcpy(Objects[STICKID+4].truename,"rod of summoning");
  strcpy(Objects[STICKID+4].cursestr,"rod of summoning");
  Objects[STICKID+4].usef=I_SUMMON;
  Objects[STICKID+4].level=2;
  Objects[STICKID+4].basevalue = 500;
  strcpy(Objects[STICKID+5].truename,"rod of hiding");
  strcpy(Objects[STICKID+5].cursestr,"rod of hiding");
  Objects[STICKID+5].usef=I_HIDE;
  Objects[STICKID+5].level=1;
  Objects[STICKID+5].basevalue = 100;
  strcpy(Objects[STICKID+6].truename,"staff of lightning bolts");
  strcpy(Objects[STICKID+6].cursestr,"staff of lightning bolts");
  Objects[STICKID+6].usef=I_LBOLT;
  Objects[STICKID+6].level=3;
  Objects[STICKID+6].basevalue = 500;
  strcpy(Objects[STICKID+7].truename,"wand of fireballs");
  strcpy(Objects[STICKID+7].cursestr,"wand of fireballs");
  Objects[STICKID+7].usef=I_FIREBALL;
  Objects[STICKID+7].level=5;
  Objects[STICKID+7].basevalue = 500;
  strcpy(Objects[STICKID+8].truename,"rod of disintegration");
  strcpy(Objects[STICKID+8].cursestr,"rod of disintegration");
  Objects[STICKID+8].usef=I_DISINTEGRATE;
  Objects[STICKID+8].level=7;
  Objects[STICKID+8].basevalue = 2000;
  strcpy(Objects[STICKID+9].truename,"staff of disruption");
  strcpy(Objects[STICKID+9].cursestr,"staff of disruption");
  Objects[STICKID+9].usef=I_DISRUPT;
  Objects[STICKID+9].level=6;
  Objects[STICKID+9].basevalue = 1000;
  strcpy(Objects[STICKID+10].truename,"snowball stick");
  strcpy(Objects[STICKID+10].cursestr,"snowball stick");
  Objects[STICKID+10].usef=I_SNOWBALL;
  Objects[STICKID+10].level=2;
  Objects[STICKID+10].basevalue = 100;
  strcpy(Objects[STICKID+11].truename,"staff of missiles");
  strcpy(Objects[STICKID+11].cursestr,"staff of missiles");
  Objects[STICKID+11].usef=I_MISSILE;
  Objects[STICKID+11].level=1;
  Objects[STICKID+11].basevalue = 50;
  strcpy(Objects[STICKID+12].truename,"rod of apportation");
  strcpy(Objects[STICKID+12].cursestr,"rod of lossage");
  Objects[STICKID+12].usef=I_APPORT;
  Objects[STICKID+12].level=2;
  Objects[STICKID+12].basevalue = 200;
  strcpy(Objects[STICKID+13].truename,"staff of dispelling");
  strcpy(Objects[STICKID+13].cursestr,"staff of self-dispelling");
  Objects[STICKID+13].usef=I_DISPEL;
  Objects[STICKID+13].level=6;
  Objects[STICKID+13].basevalue = 750;
  strcpy(Objects[STICKID+14].truename,"staff of healing");
  strcpy(Objects[STICKID+14].cursestr,"staff of harming");
  Objects[STICKID+14].usef=I_HEAL;
  Objects[STICKID+14].level=3;
  Objects[STICKID+14].basevalue = 500;
  strcpy(Objects[STICKID+15].truename,"wand of stupidity");
  strcpy(Objects[STICKID+15].cursestr,"wand of stupidity");
  Objects[STICKID+15].usef=I_POLYMORPH;
  Objects[STICKID+15].level=3;
  Objects[STICKID+15].basevalue = 1000;

  for (i=BOOTID;i<BOOTID+NUMBOOTS;i++) {
    Objects[i].objchar = BOOTS;
    Objects[i].weight = 30;
    Objects[i].fragility = 6;
    bootname(FALSE,Objects[i].objstr);
  }

  strcpy(Objects[BOOTID+0].truename,"boots of speed");
  strcpy(Objects[BOOTID+0].cursestr,"boots of slowness");
  Objects[BOOTID+0].usef = I_PERM_SPEED;
  Objects[BOOTID+0].level = 4;
  Objects[BOOTID+0].basevalue = 1000;

  strcpy(Objects[BOOTID+1].truename,"boots of heroism");
  strcpy(Objects[BOOTID+1].cursestr,"boots of cowardliness");
  Objects[BOOTID+1].usef = I_PERM_HERO;
  Objects[BOOTID+1].level = 6;
  Objects[BOOTID+1].basevalue = 1000;

  strcpy(Objects[BOOTID+2].truename,"boots of levitation");
  strcpy(Objects[BOOTID+2].cursestr,"boots of levitation");
  Objects[BOOTID+2].usef = I_PERM_LEVITATE;
  Objects[BOOTID+2].level = 3;
  Objects[BOOTID+2].basevalue = 500;

  strcpy(Objects[BOOTID+3].truename,"boots of agility");
  strcpy(Objects[BOOTID+3].cursestr,"boots of clumsiness");
  Objects[BOOTID+3].usef = I_PERM_AGILITY;
  Objects[BOOTID+3].level = 3;
  Objects[BOOTID+3].basevalue = 250;

  strcpy(Objects[BOOTID+4].truename,"jumping boots");
  strcpy(Objects[BOOTID+4].cursestr,"jumping boots");
  Objects[BOOTID+4].usef = I_BOOTS_JUMPING;
  Objects[BOOTID+4].level = 2;
  Objects[BOOTID+4].basevalue = 200;

  strcpy(Objects[BOOTID+5].truename,"boots of leather");
  strcpy(Objects[BOOTID+5].cursestr,"boots of leather");
  Objects[BOOTID+5].usef = I_NO_OP;
  Objects[BOOTID+5].level = 0;
  Objects[BOOTID+5].basevalue = 7;

  for (i=CLOAKID;i<NUMCLOAKS+CLOAKID;i++) {
    Objects[i].objchar = CLOAK;
    Objects[i].weight = 30;
    Objects[i].fragility = 4;
    cloakname(FALSE,Objects[i].objstr);
  }

  strcpy(Objects[CLOAKID+0].truename,"cloak of wool");
  strcpy(Objects[CLOAKID+0].cursestr,"cloak of wool");
  Objects[CLOAKID+0].usef = I_NO_OP;
  Objects[CLOAKID+0].level = 0;
  Objects[CLOAKID+0].basevalue = 15;

  strcpy(Objects[CLOAKID+1].truename,"cloak of negimmunity");
  strcpy(Objects[CLOAKID+1].cursestr,"cloak of level drain");
  Objects[CLOAKID+1].usef = I_PERM_NEGIMMUNE;
  Objects[CLOAKID+1].level = 3;
  Objects[CLOAKID+1].basevalue = 500;

  strcpy(Objects[CLOAKID+2].truename,"cloak of invisibility");
  strcpy(Objects[CLOAKID+2].cursestr,"cloak of invisibility");
  Objects[CLOAKID+2].usef = I_PERM_INVISIBLE;
  Objects[CLOAKID+2].level = 5;
  Objects[CLOAKID+2].basevalue = 500;

  strcpy(Objects[CLOAKID+3].truename,"cloak of skill");
  strcpy(Objects[CLOAKID+3].cursestr,"cloak of skill");
  Objects[CLOAKID+3].usef = I_PERM_ACCURACY;
  Objects[CLOAKID+3].level = 5;
  Objects[CLOAKID+3].basevalue = 1000;

  strcpy(Objects[CLOAKID+4].truename,"cloak of protection");
  strcpy(Objects[CLOAKID+4].cursestr,"cloak of damage");
  Objects[CLOAKID+4].usef = I_PERM_PROTECTION;
  Objects[CLOAKID+4].level = 3;
  Objects[CLOAKID+4].basevalue = 500;

  strcpy(Objects[CLOAKID+5].truename,"cloak of displacement");
  strcpy(Objects[CLOAKID+5].cursestr,"cloak of vulnerability");
  Objects[CLOAKID+5].usef = I_PERM_DISPLACE;
  Objects[CLOAKID+5].level = 6;
  Objects[CLOAKID+5].basevalue = 2000;

  strcpy(Objects[CLOAKID+6].truename,"cloak of true sight");
  strcpy(Objects[CLOAKID+6].cursestr,"cloak of blindness");
  Objects[CLOAKID+6].usef = I_PERM_TRUESIGHT;
  Objects[CLOAKID+6].level = 3;
  Objects[CLOAKID+6].basevalue = 500;



  for (i=RINGID;i<RINGID+NUMRINGS;i++) {
    Objects[i].objchar = RING;
    Objects[i].weight = 1;
    Objects[i].fragility = 10;
    ringname(FALSE,Objects[i].objstr);
  }

  strcpy(Objects[RINGID+0].truename,"ring of vision"); 
  strcpy(Objects[RINGID+0].cursestr,"ring of vision"); 
  Objects[RINGID+0].usef = I_PERM_VISION;
  Objects[RINGID+0].level = 1;
  Objects[RINGID+0].basevalue = 200;

  strcpy(Objects[RINGID+1].truename,"ring of burden");
  strcpy(Objects[RINGID+1].cursestr,"ring of burden");
  Objects[RINGID+1].usef = I_PERM_BURDEN;
  Objects[RINGID+1].level = 0;
  Objects[RINGID+1].blessing = -1;
  Objects[RINGID+1].basevalue = 1;

  strcpy(Objects[RINGID+2].truename,"ring of strength");
  strcpy(Objects[RINGID+2].cursestr,"ring of strength");
  Objects[RINGID+2].usef = I_PERM_STRENGTH;
  Objects[RINGID+2].level = 1;
  Objects[RINGID+2].basevalue = 100;

  strcpy(Objects[RINGID+3].truename,"ring of gaze immunity");
  strcpy(Objects[RINGID+3].cursestr,"ring of gaze immunity");
  Objects[RINGID+3].usef = I_PERM_GAZE_IMMUNE;
  Objects[RINGID+3].level = 2;
  Objects[RINGID+3].basevalue = 100;

  strcpy(Objects[RINGID+4].truename,"ring of fire resistance");
  strcpy(Objects[RINGID+4].cursestr,"ring of fire resistance");
  Objects[RINGID+4].usef = I_PERM_FIRE_RESIST;
  Objects[RINGID+4].level = 3;
  Objects[RINGID+4].basevalue = 100;

  strcpy(Objects[RINGID+5].truename,"ring of brass and glass");
  strcpy(Objects[RINGID+5].cursestr,"ring of brass and glass");
  Objects[RINGID+5].basevalue = 10;

  strcpy(Objects[RINGID+6].truename,"ring of poison resistance");
  strcpy(Objects[RINGID+6].cursestr,"ring of poison");
  Objects[RINGID+6].usef = I_PERM_POISON_RESIST;
  Objects[RINGID+6].level = 4;
  Objects[RINGID+6].basevalue = 100;

  strcpy(Objects[RINGID+7].truename,"ring of regeneration");
  strcpy(Objects[RINGID+7].cursestr,"ring of regeneration");
  Objects[RINGID+7].usef = I_PERM_REGENERATE;
  Objects[RINGID+7].level = 5;
  Objects[RINGID+7].basevalue = 1000;

  strcpy(Objects[RINGID+8].truename,"ring of self-knowledge");
  strcpy(Objects[RINGID+8].cursestr,"ring of delusion");
  Objects[RINGID+8].usef = I_PERM_KNOWLEDGE;
  Objects[RINGID+8].level = 0;
  Objects[RINGID+8].basevalue = 100;

  strcpy(Objects[RINGID+9].truename,"ring of protection");
  strcpy(Objects[RINGID+9].cursestr,"ring of vulnerability");
  Objects[RINGID+9].usef = I_PERM_PROTECTION;
  Objects[RINGID+9].level = 4;
  Objects[RINGID+9].basevalue = 500;

  /* Cash */
  strcpy(Objects[CASHID].objstr,"money");
  strcpy(Objects[CASHID].truename,"money");
  strcpy(Objects[CASHID].cursestr,"money (the root of all evil)");
  Objects[CASHID].usef = I_NO_OP;
  Objects[CASHID].objchar = CASH;
  Objects[CASHID].weight = 0;
  Objects[CASHID].level = 0;
  Objects[CASHID].fragility = 10;
  Objects[CASHID].basevalue = 0;



  /* Da Corpse. */
  strcpy(Objects[CORPSEID].objstr,"a mysterious corpse");
  strcpy(Objects[CORPSEID].truename,"a mysterious corpse");
  strcpy(Objects[CORPSEID].cursestr,"a mysterious corpse");
  Objects[CORPSEID].usef = I_CORPSE;
  Objects[CORPSEID].objchar = CORPSE;
  Objects[CORPSEID].weight = 100;
  Objects[CORPSEID].level = 0;
  Objects[CORPSEID].fragility = 10;
  Objects[CORPSEID].basevalue = 0;
  
}
